import { IDateTimeFieldValue } from '@pnp/spfx-property-controls';
import { IPropertyFieldGroupOrPerson } from '@pnp/spfx-property-controls/lib/PropertyFieldPeoplePicker';

export interface IZentalisRecognitionWallProps {
  description: string;
  isDarkTheme: boolean;
  environmentMessage: string;
  hasTeamsContext: boolean;
  userDisplayName: string;
  Header: string;
  Title: string;
  Description: string;
  LinkText: string;
  link: string;
  Icon: string;
  recognizedText1: string;
  Icon1: string;
  Description1: string;
  recognizedText2: string;
  Icon2: string;
  Description2: string;
  recognizedText3: string;
  Icon3: string;
  Description3: string;
  recognizedText4: string;
  Icon4: string;
  Description4: string;
  recognizedText5: string;
  Icon5: string;
  Description5: string;
  recognizedText6: string;
  Icon6: string;
  Description6: string;
  Date1: IDateTimeFieldValue;
  Date2: IDateTimeFieldValue;
  Date3: IDateTimeFieldValue;
  Date4: IDateTimeFieldValue;
  Date5: IDateTimeFieldValue;
  Date6: IDateTimeFieldValue;
  selectedUsers: IPropertyFieldGroupOrPerson[];
  selectedUsers1: IPropertyFieldGroupOrPerson[];
  selectedUsers2: IPropertyFieldGroupOrPerson[];
  selectedUsers3: IPropertyFieldGroupOrPerson[];
  selectedUsers4: IPropertyFieldGroupOrPerson[];
  selectedUsers5: IPropertyFieldGroupOrPerson[];
  selectedUsers6: IPropertyFieldGroupOrPerson[];
  selectedUsers7: IPropertyFieldGroupOrPerson[];
  selectedUsers8: IPropertyFieldGroupOrPerson[];
  selectedUsers9: IPropertyFieldGroupOrPerson[];
  selectedUsers10: IPropertyFieldGroupOrPerson[];
  selectedUsers11: IPropertyFieldGroupOrPerson[];
  showCard1: boolean;
  showCard2: boolean;
  showCard3: boolean;
  showCard4: boolean;
  showCard5: boolean;
  showCard6: boolean;
}

